[package]

name = "combine"
version = "1.0.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

description = "Parser combinators based on the Haskell library parsec."

repository = "https://github.com/Marwes/combine"
documentation = "https://marwes.github.io/combine/combine/index.html"

readme = "README.md"

keywords = ["parser", "combinators", "ll"]

license = "MIT"

[lib]

name = "combine"
path = "src/lib.rs"

[features]
# Using a feature in combine is considered to be unstable (does not adhere to semver) if you use one or more features
# then you have been warned that you may experience breaking changes between any release
range_stream = []
buffered_stream = []
# Feature to be passed as `cargo test --features test` making sure that all tests are run
test = ["range_stream", "buffered_stream"]
