[package]

name = "parser-combinators"
version = "0.7.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

description = "**DEPRECEATED** Parser combinators based on the Haskell library parsec. This library has been renamed to combine. See https://crates.io/crates/combine for more recent versions **DEPRECEATED**"

repository = "https://github.com/Marwes/parser-combinators"
documentation = "https://docs.rs/parser-combinators"

readme = "README.md"

keywords = ["parser", "combinators", "ll"]

license = "MIT"

[lib]

name = "parser_combinators"
path = "src/lib.rs"
