[package]

name = "combine"
version = "2.0.0-beta2"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

description = "Parser combinators based on the Haskell library parsec."

repository = "https://github.com/Marwes/combine"
documentation = "https://marwes.github.io/combine/combine/index.html"

readme = "README.md"

keywords = ["parser", "combinators", "ll"]

license = "MIT"

[lib]

name = "combine"
path = "src/lib.rs"
